# docker-compose.yml

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: agave
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U api_user -d mydb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
