"""empty message

Revision ID: 11704c1a156e
Revises: 39be7d670332
Create Date: 2014-02-04 19:21:37.385477

"""

# revision identifiers, used by Alembic.
revision = '11704c1a156e'
down_revision = '39be7d670332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=140), nullable=True),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_sources')
    ### end Alembic commands ###
