"""empty message

Revision ID: 16f2a4c577ef
Revises: 2b8d4dacdf83
Create Date: 2014-04-29 15:53:10.337845

"""

# revision identifiers, used by Alembic.
revision = '16f2a4c577ef'
down_revision = '2b8d4dacdf83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    ### end Alembic commands ###
