"""empty message

Revision ID: 1a5406d2974e
Revises: None
Create Date: 2014-02-01 11:36:12.561738

"""

# revision identifiers, used by Alembic.
revision = '1a5406d2974e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('notes', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'notes')
    ### end Alembic commands ###
