"""empty message

Revision ID: 2a256286b3c3
Revises: None
Create Date: 2014-04-30 14:51:29.970080

"""

# revision identifiers, used by Alembic.
revision = '2a256286b3c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwd_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashstr', sa.String(length=40), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwd_reset')
    ### end Alembic commands ###
