"""empty message

Revision ID: 2b8d4dacdf83
Revises: 2e1967800ef9
Create Date: 2014-03-22 00:43:08.025387

"""

# revision identifiers, used by Alembic.
revision = '2b8d4dacdf83'
down_revision = '2e1967800ef9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attacks', sa.Column('signature', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attacks', 'signature')
    ### end Alembic commands ###
