"""empty message

Revision ID: 2e1967800ef9
Revises: 11704c1a156e
Create Date: 2014-02-07 21:47:13.524268

"""

# revision identifiers, used by Alembic.
revision = '2e1967800ef9'
down_revision = '11704c1a156e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tar_uploads')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tar_uploads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
