"""empty message

Revision ID: 39be7d670332
Revises: a3a083ff59c
Create Date: 2014-02-04 18:27:06.277188

"""

# revision identifiers, used by Alembic.
revision = '39be7d670332'
down_revision = 'a3a083ff59c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tar_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tar_uploads')
    ### end Alembic commands ###
