"""empty message

Revision ID: a3a083ff59c
Revises: 1a5406d2974e
Create Date: 2014-02-02 22:19:21.937924

"""

# revision identifiers, used by Alembic.
revision = 'a3a083ff59c'
down_revision = '1a5406d2974e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script', sa.String(length=102400), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploy_scripts')
    ### end Alembic commands ###
